# Generated by Django 5.0.1 on 2024-02-14 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='costumuser',
            old_name='adress',
            new_name='address',
        ),
    ]
